export const playerData = [
	{
		rank: 1,
		gamerank: 1,
		firstName: "Trent",
		lastName: "Williams",
		image: "/images/player-image.png",
		ps: "T",
		ht: "6-5",
		wt: 320,
		age: 36,
		exp: 15,
		college: "Oklahoma",
		honors: ["Pro Bowl (x10)", "First-team All-Pro (x2)"],
		background:
			"Trent Williams is widely regarded as one of the best offensive tackles in the NFL, known for his physicality and leadership on and off the field.",
		careerStats: {
			gamesPlayed: 171,
			gamesStarted: 170,
			penalties: 10,
			sacksAllowed: 15,
		},
		notableAchievements: [
			"Drafted #4 overall in 2010 NFL Draft",
			"Named to NFL 2010s All-Decade Team",
		],
	},
	{
		rank: 2,
		gamerank: 10,
		firstName: "Aaron",
		lastName: "Rodgers",
		ps: "QB",
		image: "/images/player-image.png",
		ht: "6-2",
		wt: 225,
		age: 39,
		exp: 18,
		college: "California",
		honors: ["Super Bowl Champion", "4x NFL MVP"],
		background:
			"Aaron Rodgers is one of the most talented and decorated quarterbacks in NFL history, known for his precision passing and football IQ.",
		careerStats: {
			passingYards: 59055,
			touchdowns: 475,
			interceptions: 103,
			passerRating: 103.6,
		},
		notableAchievements: [
			"Super Bowl XLV MVP",
			"Holds the NFL's lowest career interception percentage (1.3%)",
		],
	},
	{
		rank: 3,
		gamerank: 71,
		firstName: "Tom",
		lastName: "Brady",
		ps: "QB",
		ht: "6-4",
		image: "/images/player-image.png",
		wt: 225,
		age: 46,
		exp: 23,
		college: "Michigan",
		honors: ["7x Super Bowl Champion", "3x NFL MVP"],
		background:
			"Tom Brady, often referred to as the greatest quarterback of all time, has an unmatched resume, leading his teams to multiple Super Bowl victories.",
		careerStats: {
			passingYards: 89114,
			touchdowns: 649,
			interceptions: 212,
			passerRating: 97.2,
		},
		notableAchievements: [
			"Most Super Bowl wins (7) by a player",
			"NFL's all-time leader in passing yards and touchdowns",
		],
	},
	{
		rank: 4,
		gamerank: 74,
		firstName: "Patrick",
		lastName: "Mahomes",
		ps: "QB",
		image: "/images/player-image.png",
		ht: "6-3",
		wt: 230,
		age: 28,
		exp: 6,
		college: "Texas Tech",
		honors: ["2x Super Bowl Champion", "2x Super Bowl MVP", "2x NFL MVP"],
		background:
			"Patrick Mahomes is redefining the quarterback position with his dynamic playmaking ability and leadership in pressure situations.",
		careerStats: {
			passingYards: 24364,
			touchdowns: 192,
			interceptions: 49,
			passerRating: 108.7,
		},
		notableAchievements: [
			"NFL MVP in 2018 and 2022",
			"Led Chiefs to two Super Bowl victories",
		],
	},
	{
		rank: 5,
		gamerank: 11,
		firstName: "Davante",
		lastName: "Adams",
		ps: "WR",
		image: "/images/player-image.png",
		ht: "6-1",
		wt: 215,
		age: 31,
		exp: 10,
		college: "Fresno State",
		honors: ["First-team All-Pro (x3)", "Pro Bowl (x6)"],
		background:
			"Davante Adams is widely recognized as one of the NFL's top wide receivers, known for his route running and catching ability.",
		careerStats: {
			receptions: 764,
			receivingYards: 9208,
			touchdowns: 82,
		},
		notableAchievements: [
			"Led the NFL in receiving touchdowns in 2020",
			"Over 1,500 receiving yards in 2022",
		],
	},
	{
		rank: 6,
		gamerank: 30,
		firstName: "Trent",
		lastName: "Williams",
		ps: "T",
		ht: "6-5",
		image: "/images/player-image.png",
		wt: 320,
		age: 36,
		exp: 15,
		college: "Oklahoma",
		honors: ["Pro Bowl (x10)", "First-team All-Pro (x2)"],
		background:
			"Trent Williams is widely regarded as one of the best offensive tackles in the NFL, known for his physicality and leadership on and off the field.",
		careerStats: {
			gamesPlayed: 171,
			gamesStarted: 170,
			penalties: 10,
			sacksAllowed: 15,
		},
		notableAchievements: [
			"Drafted #4 overall in 2010 NFL Draft",
			"Named to NFL 2010s All-Decade Team",
		],
	},
	{
		rank: 7,
		gamerank: 12,
		firstName: "Aaron",
		lastName: "Rodgers",
		ps: "QB",
		ht: "6-2",
		image: "/images/player-image.png",
		wt: 225,
		age: 39,
		exp: 18,
		college: "California",
		honors: ["Super Bowl Champion", "4x NFL MVP"],
		background:
			"Aaron Rodgers is one of the most talented and decorated quarterbacks in NFL history, known for his precision passing and football IQ.",
		careerStats: {
			passingYards: 59055,
			touchdowns: 475,
			interceptions: 103,
			passerRating: 103.6,
		},
		notableAchievements: [
			"Super Bowl XLV MVP",
			"Holds the NFL's lowest career interception percentage (1.3%)",
		],
	},
	{
		rank: 8,
		gamerank: 13,
		firstName: "Tom",
		lastName: "Brady",
		ps: "QB",
		ht: "6-4",
		wt: 225,
		age: 46,
		exp: 23,
		college: "Michigan",
		honors: ["7x Super Bowl Champion", "3x NFL MVP"],
		background:
			"Tom Brady, often referred to as the greatest quarterback of all time, has an unmatched resume, leading his teams to multiple Super Bowl victories.",
		careerStats: {
			passingYards: 89114,
			touchdowns: 649,
			interceptions: 212,
			passerRating: 97.2,
		},
		notableAchievements: [
			"Most Super Bowl wins (7) by a player",
			"NFL's all-time leader in passing yards and touchdowns",
		],
	},
	{
		rank: 9,
		gamerank: 14,
		firstName: "Patrick",
		lastName: "Mahomes",
		ps: "QB",
		ht: "6-3",
		wt: 230,
		age: 28,
		exp: 6,
		college: "Texas Tech",
		honors: ["2x Super Bowl Champion", "2x Super Bowl MVP", "2x NFL MVP"],
		background:
			"Patrick Mahomes is redefining the quarterback position with his dynamic playmaking ability and leadership in pressure situations.",
		careerStats: {
			passingYards: 24364,
			touchdowns: 192,
			interceptions: 49,
			passerRating: 108.7,
		},
		notableAchievements: [
			"NFL MVP in 2018 and 2022",
			"Led Chiefs to two Super Bowl victories",
		],
	},
	{
		rank: 10,
		gamerank: 15,
		firstName: "Davante",
		lastName: "Adams",
		ps: "WR",
		ht: "6-1",
		wt: 215,
		age: 31,
		exp: 10,
		college: "Fresno State",
		honors: ["First-team All-Pro (x3)", "Pro Bowl (x6)"],
		background:
			"Davante Adams is widely recognized as one of the NFL's top wide receivers, known for his route running and catching ability.",
		careerStats: {
			receptions: 764,
			receivingYards: 9208,
			touchdowns: 82,
		},
		notableAchievements: [
			"Led the NFL in receiving touchdowns in 2020",
			"Over 1,500 receiving yards in 2022",
		],
	},
	{
		rank: 11,
		gamerank: 15,
		firstName: "Davante",
		lastName: "Adams",
		ps: "WR",
		ht: "6-1",
		wt: 215,
		age: 31,
		exp: 10,
		college: "Fresno State",
		honors: ["First-team All-Pro (x3)", "Pro Bowl (x6)"],
		background:
			"Davante Adams is widely recognized as one of the NFL's top wide receivers, known for his route running and catching ability.",
		careerStats: {
			receptions: 764,
			receivingYards: 9208,
			touchdowns: 82,
		},
		notableAchievements: [
			"Led the NFL in receiving touchdowns in 2020",
			"Over 1,500 receiving yards in 2022",
		],
	},
	{
		rank: 12,
		gamerank: 15,
		firstName: "Davante",
		lastName: "Adams",
		ps: "WR",
		ht: "6-1",
		wt: 215,
		age: 31,
		exp: 10,
		college: "Fresno State",
		honors: ["First-team All-Pro (x3)", "Pro Bowl (x6)"],
		background:
			"Davante Adams is widely recognized as one of the NFL's top wide receivers, known for his route running and catching ability.",
		careerStats: {
			receptions: 764,
			receivingYards: 9208,
			touchdowns: 82,
		},
		notableAchievements: [
			"Led the NFL in receiving touchdowns in 2020",
			"Over 1,500 receiving yards in 2022",
		],
	},
	{
		rank: 13,
		gamerank: 15,
		firstName: "Davante",
		lastName: "Adams",
		ps: "WR",
		ht: "6-1",
		wt: 215,
		age: 31,
		exp: 10,
		college: "Fresno State",
		honors: ["First-team All-Pro (x3)", "Pro Bowl (x6)"],
		background:
			"Davante Adams is widely recognized as one of the NFL's top wide receivers, known for his route running and catching ability.",
		careerStats: {
			receptions: 764,
			receivingYards: 9208,
			touchdowns: 82,
		},
		notableAchievements: [
			"Led the NFL in receiving touchdowns in 2020",
			"Over 1,500 receiving yards in 2022",
		],
	},
	{
		rank: 14,
		gamerank: 15,
		firstName: "Davante",
		lastName: "Adams",
		ps: "WR",
		ht: "6-1",
		wt: 215,
		age: 31,
		exp: 10,
		college: "Fresno State",
		honors: ["First-team All-Pro (x3)", "Pro Bowl (x6)"],
		background:
			"Davante Adams is widely recognized as one of the NFL's top wide receivers, known for his route running and catching ability.",
		careerStats: {
			receptions: 764,
			receivingYards: 9208,
			touchdowns: 82,
		},
		notableAchievements: [
			"Led the NFL in receiving touchdowns in 2020",
			"Over 1,500 receiving yards in 2022",
		],
	},
	{
		rank: 15,
		gamerank: 15,
		firstName: "Davante",
		lastName: "Adams",
		ps: "WR",
		ht: "6-1",
		wt: 215,
		age: 31,
		exp: 10,
		college: "Fresno State",
		honors: ["First-team All-Pro (x3)", "Pro Bowl (x6)"],
		background:
			"Davante Adams is widely recognized as one of the NFL's top wide receivers, known for his route running and catching ability.",
		careerStats: {
			receptions: 764,
			receivingYards: 9208,
			touchdowns: 82,
		},
		notableAchievements: [
			"Led the NFL in receiving touchdowns in 2020",
			"Over 1,500 receiving yards in 2022",
		],
	},
];
